exports.PORT = process.env.PORT || 5000;
exports.NODEMAILER_USER = process.env.NODEMAILER_USER;
exports.NODEMAILER_CLIENT_ID = process.env.NODEMAILER_CLIENT_ID;
exports.NODEMAILER_CLIENT_SECRET = process.env.NODEMAILER_CLIENT_SECRET;
exports.NODEMAILER_REFRESH_TOKEN = process.env.NODEMAILER_REFRESH_TOKEN;
exports.NODEMAILER_ACCESS_TOKEN = process.env.NODEMAILER_ACCESS_TOKEN;
